### ISSUE TITLE
FreeBoard modify process

### ISSUE THREAD

**Issue by LeeJiHyeong** [LeeJiHyeong/spg#46]
I'm having trouble implementing the freeBoard modify.

When uploading a content by modifying the file, 

the process of deleting the existing file from the server must be performed.

Controller name of modify page is goFreeBoardModify in BoardController.java

**Comment by kihwankim** [comment]
okay I will fix that kind of problem and push this and can you tell me the method name which you would like to change or fix. there are not detail thing I can distinguish

**Comment by LeeJiHyeong** [comment]
Thank you ><
